CREATE TABLE `paises` (
  `id` int(11) UNSIGNED NOT NULL auto_increment,
  `nombre` varchar(128) default NULL,
  `name` varchar(128) default NULL,
  `nom` varchar(128) default NULL,
  `iso2` char(5) default NULL,
  `iso3` char(5) default NULL,
  `phone_code` varchar(5)default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `paises` VALUES(NULL,'Afganistán','Afghanistan','Afghanistan','AF','AFG','93');
INSERT INTO `paises` VALUES(NULL,'Albania','Albania','Albanie','AL','ALB','355');
INSERT INTO `paises` VALUES(NULL,'Alemania','Germany','Allemagne','DE','DEU','49');
INSERT INTO `paises` VALUES(NULL,'Andorra','Andorra','Andorra','AD','AND','376');
INSERT INTO `paises` VALUES(NULL,'Angola','Angola','Angola','AO','AGO','244');
INSERT INTO `paises` VALUES(NULL,'Anguila','Anguilla','Anguilla','AI','AIA','1 264');
INSERT INTO `paises` VALUES(NULL,'Antártida','Antarctica','L Antarctique','AQ','ATA','672');
INSERT INTO `paises` VALUES(NULL,'Antigua y Barbuda','Antigua and Barbuda','Antigua et Barbuda','AG','ATG','1 268');
INSERT INTO `paises` VALUES(NULL,'Arabia Saudita','Saudi Arabia','Arabie Saoudite','SA','SAU','966');
INSERT INTO `paises` VALUES(NULL,'Argelia','Algeria','Algérie','DZ','DZA','213');
INSERT INTO `paises` VALUES(NULL,'Argentina','Argentina','Argentine','AR','ARG','54');
INSERT INTO `paises` VALUES(NULL,'Armenia','Armenia','L Arménie','AM','ARM','374');
INSERT INTO `paises` VALUES(NULL,'Aruba','Aruba','Aruba','AW','ABW','297');
INSERT INTO `paises` VALUES(NULL,'Australia','Australia','Australie','AU','AUS','61');
INSERT INTO `paises` VALUES(NULL,'Austria','Austria','Autriche','AT','AUT','43');
INSERT INTO `paises` VALUES(NULL,'Azerbaiyán','Azerbaijan','L Azerbaïdjan','AZ','AZE','994');
INSERT INTO `paises` VALUES(NULL,'Bélgica','Belgium','Belgique','BE','BEL','32');
INSERT INTO `paises` VALUES(NULL,'Bahamas','Bahamas','Bahamas','BS','BHS','1 242');
INSERT INTO `paises` VALUES(NULL,'Bahrein','Bahrain','Bahreïn','BH','BHR','973');
INSERT INTO `paises` VALUES(NULL,'Bangladesh','Bangladesh','Bangladesh','BD','BGD','880');
INSERT INTO `paises` VALUES(NULL,'Barbados','Barbados','Barbade','BB','BRB','1 246');
INSERT INTO `paises` VALUES(NULL,'Belice','Belize','Belize','BZ','BLZ','501');
INSERT INTO `paises` VALUES(NULL,'Benín','Benin','Bénin','BJ','BEN','229');
INSERT INTO `paises` VALUES(NULL,'Bhután','Bhutan','Le Bhoutan','BT','BTN','975');
INSERT INTO `paises` VALUES(NULL,'Bielorrusia','Belarus','Biélorussie','BY','BLR','375');
INSERT INTO `paises` VALUES(NULL,'Birmania','Myanmar','Myanmar','MM','MMR','95');
INSERT INTO `paises` VALUES(NULL,'Bolivia','Bolivia','Bolivie','BO','BOL','591');
INSERT INTO `paises` VALUES(NULL,'Bosnia y Herzegovina','Bosnia and Herzegovina','Bosnie-Herzégovine','BA','BIH','387');
INSERT INTO `paises` VALUES(NULL,'Botsuana','Botswana','Botswana','BW','BWA','267');
INSERT INTO `paises` VALUES(NULL,'Brasil','Brazil','Brésil','BR','BRA','55');
INSERT INTO `paises` VALUES(NULL,'Brunéi','Brunei','Brunei','BN','BRN','673');
INSERT INTO `paises` VALUES(NULL,'Bulgaria','Bulgaria','Bulgarie','BG','BGR','359');
INSERT INTO `paises` VALUES(NULL,'Burkina Faso','Burkina Faso','Burkina Faso','BF','BFA','226');
INSERT INTO `paises` VALUES(NULL,'Burundi','Burundi','Burundi','BI','BDI','257');
INSERT INTO `paises` VALUES(NULL,'Cabo Verde','Cape Verde','Cap-Vert','CV','CPV','238');
INSERT INTO `paises` VALUES(NULL,'Camboya','Cambodia','Cambodge','KH','KHM','855');
INSERT INTO `paises` VALUES(NULL,'Camerún','Cameroon','Cameroun','CM','CMR','237');
INSERT INTO `paises` VALUES(NULL,'Canadá','Canada','Canada','CA','CAN','1');
INSERT INTO `paises` VALUES(NULL,'Chad','Chad','Tchad','TD','TCD','235');
INSERT INTO `paises` VALUES(NULL,'Chile','Chile','Chili','CL','CHL','56');
INSERT INTO `paises` VALUES(NULL,'China','China','Chine','CN','CHN','86');
INSERT INTO `paises` VALUES(NULL,'Chipre','Cyprus','Chypre','CY','CYP','357');
INSERT INTO `paises` VALUES(NULL,'Ciudad del Vaticano','Vatican City State','Cité du Vatican','VA','VAT','39');
INSERT INTO `paises` VALUES(NULL,'Colombia','Colombia','Colombie','CO','COL','57');
INSERT INTO `paises` VALUES(NULL,'Comoras','Comoros','Comores','KM','COM','269');
INSERT INTO `paises` VALUES(NULL,'República del Congo','Republic of the Congo','République du Congo','CG','COG','242');
INSERT INTO `paises` VALUES(NULL,'República Democrática del Congo','Democratic Republic of the Congo','République démocratique du Congo','CD','COD','243');
INSERT INTO `paises` VALUES(NULL,'Corea del Norte','North Korea','Corée du Nord','KP','PRK','850');
INSERT INTO `paises` VALUES(NULL,'Corea del Sur','South Korea','Corée du Sud','KR','KOR','82');
INSERT INTO `paises` VALUES(NULL,'Costa de Marfil','Ivory Coast','Côte-d Ivoire','CI','CIV','225');
INSERT INTO `paises` VALUES(NULL,'Costa Rica','Costa Rica','Costa Rica','CR','CRI','506');
INSERT INTO `paises` VALUES(NULL,'Croacia','Croatia','Croatie','HR','HRV','385');
INSERT INTO `paises` VALUES(NULL,'Cuba','Cuba','Cuba','CU','CUB','53');
INSERT INTO `paises` VALUES(NULL,'Curazao','Curaçao','Curaçao','CW','CWU','5999');
INSERT INTO `paises` VALUES(NULL,'Dinamarca','Denmark','Danemark','DK','DNK','45');
INSERT INTO `paises` VALUES(NULL,'Dominica','Dominica','Dominique','DM','DMA','1 767');
INSERT INTO `paises` VALUES(NULL,'Ecuador','Ecuador','Equateur','EC','ECU','593');
INSERT INTO `paises` VALUES(NULL,'Egipto','Egypt','Egypte','EG','EGY','20');
INSERT INTO `paises` VALUES(NULL,'El Salvador','El Salvador','El Salvador','SV','SLV','503');
INSERT INTO `paises` VALUES(NULL,'Emiratos Árabes Unidos','United Arab Emirates','Emirats Arabes Unis','AE','ARE','971');
INSERT INTO `paises` VALUES(NULL,'Eritrea','Eritrea','Erythrée','ER','ERI','291');
INSERT INTO `paises` VALUES(NULL,'Eslovaquia','Slovakia','Slovaquie','SK','SVK','421');
INSERT INTO `paises` VALUES(NULL,'Eslovenia','Slovenia','Slovénie','SI','SVN','386');
INSERT INTO `paises` VALUES(NULL,'España','Spain','Espagne','ES','ESP','34');
INSERT INTO `paises` VALUES(NULL,'Estados Unidos de América','United States of America','États-Unis d Amérique','US','USA','1');
INSERT INTO `paises` VALUES(NULL,'Estonia','Estonia','L Estonie','EE','EST','372');
INSERT INTO `paises` VALUES(NULL,'Etiopía','Ethiopia','Ethiopie','ET','ETH','251');
INSERT INTO `paises` VALUES(NULL,'Filipinas','Philippines','Philippines','PH','PHL','63');
INSERT INTO `paises` VALUES(NULL,'Finlandia','Finland','Finlande','FI','FIN','358');
INSERT INTO `paises` VALUES(NULL,'Fiyi','Fiji','Fidji','FJ','FJI','679');
INSERT INTO `paises` VALUES(NULL,'Francia','France','France','FR','FRA','33');
INSERT INTO `paises` VALUES(NULL,'Gabón','Gabon','Gabon','GA','GAB','241');
INSERT INTO `paises` VALUES(NULL,'Gambia','Gambia','Gambie','GM','GMB','220');
INSERT INTO `paises` VALUES(NULL,'Georgia','Georgia','Géorgie','GE','GEO','995');
INSERT INTO `paises` VALUES(NULL,'Ghana','Ghana','Ghana','GH','GHA','233');
INSERT INTO `paises` VALUES(NULL,'Gibraltar','Gibraltar','Gibraltar','GI','GIB','350');
INSERT INTO `paises` VALUES(NULL,'Granada','Grenada','Grenade','GD','GRD','1 473');
INSERT INTO `paises` VALUES(NULL,'Grecia','Greece','Grèce','GR','GRC','30');
INSERT INTO `paises` VALUES(NULL,'Groenlandia','Greenland','Groenland','GL','GRL','299');
INSERT INTO `paises` VALUES(NULL,'Guadalupe','Guadeloupe','Guadeloupe','GP','GLP','590');
INSERT INTO `paises` VALUES(NULL,'Guam','Guam','Guam','GU','GUM','1 671');
INSERT INTO `paises` VALUES(NULL,'Guatemala','Guatemala','Guatemala','GT','GTM','502');
INSERT INTO `paises` VALUES(NULL,'Guayana Francesa','French Guiana','Guyane française','GF','GUF','594');
INSERT INTO `paises` VALUES(NULL,'Guernsey','Guernsey','Guernesey','GG','GGY','44');
INSERT INTO `paises` VALUES(NULL,'Guinea','Guinea','Guinée','GN','GIN','224');
INSERT INTO `paises` VALUES(NULL,'Guinea Ecuatorial','Equatorial Guinea','Guinée Equatoriale','GQ','GNQ','240');
INSERT INTO `paises` VALUES(NULL,'Guinea-Bissau','Guinea-Bissau','Guinée-Bissau','GW','GNB','245');
INSERT INTO `paises` VALUES(NULL,'Guyana','Guyana','Guyane','GY','GUY','592');
INSERT INTO `paises` VALUES(NULL,'Haití','Haiti','Haïti','HT','HTI','509');
INSERT INTO `paises` VALUES(NULL,'Honduras','Honduras','Honduras','HN','HND','504');
INSERT INTO `paises` VALUES(NULL,'Hong kong','Hong Kong','Hong Kong','HK','HKG','852');
INSERT INTO `paises` VALUES(NULL,'Hungría','Hungary','Hongrie','HU','HUN','36');
INSERT INTO `paises` VALUES(NULL,'India','India','Inde','IN','IND','91');
INSERT INTO `paises` VALUES(NULL,'Indonesia','Indonesia','Indonésie','ID','IDN','62');
INSERT INTO `paises` VALUES(NULL,'Irán','Iran','Iran','IR','IRN','98');
INSERT INTO `paises` VALUES(NULL,'Irak','Iraq','Irak','IQ','IRQ','964');
INSERT INTO `paises` VALUES(NULL,'Irlanda','Ireland','Irlande','IE','IRL','353');
INSERT INTO `paises` VALUES(NULL,'Isla Bouvet','Bouvet Island','Bouvet Island','BV','BVT','');
INSERT INTO `paises` VALUES(NULL,'Isla de Man','Isle of Man','Ile de Man','IM','IMN','44');
INSERT INTO `paises` VALUES(NULL,'Isla de Navidad','Christmas Island','Christmas Island','CX','CXR','61');
INSERT INTO `paises` VALUES(NULL,'Isla Norfolk','Norfolk Island','Île de Norfolk','NF','NFK','672');
INSERT INTO `paises` VALUES(NULL,'Islandia','Iceland','Islande','IS','ISL','354');
INSERT INTO `paises` VALUES(NULL,'Islas Bermudas','Bermuda Islands','Bermudes','BM','BMU','1 441');
INSERT INTO `paises` VALUES(NULL,'Islas Caimán','Cayman Islands','Iles Caïmans','KY','CYM','1 345');
INSERT INTO `paises` VALUES(NULL,'Islas Cocos (Keeling);','Cocos (Keeling); Islands','Cocos Keeling','CC','CCK','61');
INSERT INTO `paises` VALUES(NULL,'Islas Cook','Cook Islands','Iles Cook','CK','COK','682');
INSERT INTO `paises` VALUES(NULL,'Islas de Åland','Åland Islands','Îles Åland','AX','ALA','358');
INSERT INTO `paises` VALUES(NULL,'Islas Feroe','Faroe Islands','Iles Féro','FO','FRO','298');
INSERT INTO `paises` VALUES(NULL,'Islas Georgias del Sur y Sandwich del Sur','South Georgia and the South Sandwich Islands','Géorgie du Sud et les Îles Sandwich du Sud','GS','SGS','500');
INSERT INTO `paises` VALUES(NULL,'Islas Heard y McDonald','Heard Island and McDonald Islands','Les îles Heard et McDonald','HM','HMD','');
INSERT INTO `paises` VALUES(NULL,'Islas Maldivas','Maldives','Maldives','MV','MDV','960');
INSERT INTO `paises` VALUES(NULL,'Islas Malvinas','Falkland Islands (Malvinas);','Malvinas','FK','FLK','500');
INSERT INTO `paises` VALUES(NULL,'Islas Marianas del Norte','Northern Mariana Islands','Iles Mariannes du Nord','MP','MNP','1 670');
INSERT INTO `paises` VALUES(NULL,'Islas Marshall','Marshall Islands','Iles Marshall','MH','MHL','692');
INSERT INTO `paises` VALUES(NULL,'Islas Pitcairn','Pitcairn Islands','Iles Pitcairn','PN','PCN','870');
INSERT INTO `paises` VALUES(NULL,'Islas Salomón','Solomon Islands','Iles Salomon','SB','SLB','677');
INSERT INTO `paises` VALUES(NULL,'Islas Turcas y Caicos','Turks and Caicos Islands','Iles Turques et Caïques','TC','TCA','1 649');
INSERT INTO `paises` VALUES(NULL,'Islas Ultramarinas Menores de Estados Unidos','United States Minor Outlying Islands','États-Unis Îles mineures éloignées','UM','UMI','246');
INSERT INTO `paises` VALUES(NULL,'Islas Vírgenes Británicas','Virgin Islands','Iles Vierges','VG','VGB','1 284');
INSERT INTO `paises` VALUES(NULL,'Islas Vírgenes de los Estados Unidos','United States Virgin Islands','Îles Vierges américaines','VI','VIR','1 340');
INSERT INTO `paises` VALUES(NULL,'Israel','Israel','Israël','IL','ISR','972');
INSERT INTO `paises` VALUES(NULL,'Italia','Italy','Italie','IT','ITA','39');
INSERT INTO `paises` VALUES(NULL,'Jamaica','Jamaica','Jamaïque','JM','JAM','1 876');
INSERT INTO `paises` VALUES(NULL,'Japón','Japan','Japon','JP','JPN','81');
INSERT INTO `paises` VALUES(NULL,'Jersey','Jersey','Maillot','JE','JEY','44');
INSERT INTO `paises` VALUES(NULL,'Jordania','Jordan','Jordan','JO','JOR','962');
INSERT INTO `paises` VALUES(NULL,'Kazajistán','Kazakhstan','Le Kazakhstan','KZ','KAZ','7');
INSERT INTO `paises` VALUES(NULL,'Kenia','Kenya','Kenya','KE','KEN','254');
INSERT INTO `paises` VALUES(NULL,'Kirguistán','Kyrgyzstan','Kirghizstan','KG','KGZ','996');
INSERT INTO `paises` VALUES(NULL,'Kiribati','Kiribati','Kiribati','KI','KIR','686');
INSERT INTO `paises` VALUES(NULL,'Kuwait','Kuwait','Koweït','KW','KWT','965');
INSERT INTO `paises` VALUES(NULL,'Líbano','Lebanon','Liban','LB','LBN','961');
INSERT INTO `paises` VALUES(NULL,'Laos','Laos','Laos','LA','LAO','856');
INSERT INTO `paises` VALUES(NULL,'Lesoto','Lesotho','Lesotho','LS','LSO','266');
INSERT INTO `paises` VALUES(NULL,'Letonia','Latvia','La Lettonie','LV','LVA','371');
INSERT INTO `paises` VALUES(NULL,'Liberia','Liberia','Liberia','LR','LBR','231');
INSERT INTO `paises` VALUES(NULL,'Libia','Libya','Libye','LY','LBY','218');
INSERT INTO `paises` VALUES(NULL,'Liechtenstein','Liechtenstein','Liechtenstein','LI','LIE','423');
INSERT INTO `paises` VALUES(NULL,'Lituania','Lithuania','La Lituanie','LT','LTU','370');
INSERT INTO `paises` VALUES(NULL,'Luxemburgo','Luxembourg','Luxembourg','LU','LUX','352');
INSERT INTO `paises` VALUES(NULL,'México','Mexico','Mexique','MX','MEX','52');
INSERT INTO `paises` VALUES(NULL,'Mónaco','Monaco','Monaco','MC','MCO','377');
INSERT INTO `paises` VALUES(NULL,'Macao','Macao','Macao','MO','MAC','853');
INSERT INTO `paises` VALUES(NULL,'Macedônia','Macedonia','Macédoine','MK','MKD','389');
INSERT INTO `paises` VALUES(NULL,'Madagascar','Madagascar','Madagascar','MG','MDG','261');
INSERT INTO `paises` VALUES(NULL,'Malasia','Malaysia','Malaisie','MY','MYS','60');
INSERT INTO `paises` VALUES(NULL,'Malawi','Malawi','Malawi','MW','MWI','265');
INSERT INTO `paises` VALUES(NULL,'Mali','Mali','Mali','ML','MLI','223');
INSERT INTO `paises` VALUES(NULL,'Malta','Malta','Malte','MT','MLT','356');
INSERT INTO `paises` VALUES(NULL,'Marruecos','Morocco','Maroc','MA','MAR','212');
INSERT INTO `paises` VALUES(NULL,'Martinica','Martinique','Martinique','MQ','MTQ','596');
INSERT INTO `paises` VALUES(NULL,'Mauricio','Mauritius','Iles Maurice','MU','MUS','230');
INSERT INTO `paises` VALUES(NULL,'Mauritania','Mauritania','Mauritanie','MR','MRT','222');
INSERT INTO `paises` VALUES(NULL,'Mayotte','Mayotte','Mayotte','YT','MYT','262');
INSERT INTO `paises` VALUES(NULL,'Micronesia','Estados Federados de','Federados Estados de','FM','FSM','691');
INSERT INTO `paises` VALUES(NULL,'Moldavia','Moldova','Moldavie','MD','MDA','373');
INSERT INTO `paises` VALUES(NULL,'Mongolia','Mongolia','Mongolie','MN','MNG','976');
INSERT INTO `paises` VALUES(NULL,'Montenegro','Montenegro','Monténégro','ME','MNE','382');
INSERT INTO `paises` VALUES(NULL,'Montserrat','Montserrat','Montserrat','MS','MSR','1 664');
INSERT INTO `paises` VALUES(NULL,'Mozambique','Mozambique','Mozambique','MZ','MOZ','258');
INSERT INTO `paises` VALUES(NULL,'Namibia','Namibia','Namibie','NA','NAM','264');
INSERT INTO `paises` VALUES(NULL,'Nauru','Nauru','Nauru','NR','NRU','674');
INSERT INTO `paises` VALUES(NULL,'Nepal','Nepal','Népal','NP','NPL','977');
INSERT INTO `paises` VALUES(NULL,'Nicaragua','Nicaragua','Nicaragua','NI','NIC','505');
INSERT INTO `paises` VALUES(NULL,'Niger','Niger','Niger','NE','NER','227');
INSERT INTO `paises` VALUES(NULL,'Nigeria','Nigeria','Nigeria','NG','NGA','234');
INSERT INTO `paises` VALUES(NULL,'Niue','Niue','Niou','NU','NIU','683');
INSERT INTO `paises` VALUES(NULL,'Noruega','Norway','Norvège','NO','NOR','47');
INSERT INTO `paises` VALUES(NULL,'Nueva Caledonia','New Caledonia','Nouvelle-Calédonie','NC','NCL','687');
INSERT INTO `paises` VALUES(NULL,'Nueva Zelanda','New Zealand','Nouvelle-Zélande','NZ','NZL','64');
INSERT INTO `paises` VALUES(NULL,'Omán','Oman','Oman','OM','OMN','968');
INSERT INTO `paises` VALUES(NULL,'Países Bajos','Netherlands','Pays-Bas','NL','NLD','31');
INSERT INTO `paises` VALUES(NULL,'Pakistán','Pakistan','Pakistan','PK','PAK','92');
INSERT INTO `paises` VALUES(NULL,'Palau','Palau','Palau','PW','PLW','680');
INSERT INTO `paises` VALUES(NULL,'Palestina','Palestine','La Palestine','PS','PSE','970');
INSERT INTO `paises` VALUES(NULL,'Panamá','Panama','Panama','PA','PAN','507');
INSERT INTO `paises` VALUES(NULL,'Papúa Nueva Guinea','Papua New Guinea','Papouasie-Nouvelle-Guinée','PG','PNG','675');
INSERT INTO `paises` VALUES(NULL,'Paraguay','Paraguay','Paraguay','PY','PRY','595');
INSERT INTO `paises` VALUES(NULL,'Perú','Peru','Pérou','PE','PER','51');
INSERT INTO `paises` VALUES(NULL,'Polinesia Francesa','French Polynesia','Polynésie française','PF','PYF','689');
INSERT INTO `paises` VALUES(NULL,'Polonia','Poland','Pologne','PL','POL','48');
INSERT INTO `paises` VALUES(NULL,'Portugal','Portugal','Portugal','PT','PRT','351');
INSERT INTO `paises` VALUES(NULL,'Puerto Rico','Puerto Rico','Porto Rico','PR','PRI','1');
INSERT INTO `paises` VALUES(NULL,'Qatar','Qatar','Qatar','QA','QAT','974');
INSERT INTO `paises` VALUES(NULL,'Reino Unido','United Kingdom','Royaume-Uni','GB','GBR','44');
INSERT INTO `paises` VALUES(NULL,'República Centroafricana','Central African Republic','République Centrafricaine','CF','CAF','236');
INSERT INTO `paises` VALUES(NULL,'República Checa','Czech Republic','République Tchèque','CZ','CZE','420');
INSERT INTO `paises` VALUES(NULL,'República Dominicana','Dominican Republic','République Dominicaine','DO','DOM','1 809');
INSERT INTO `paises` VALUES(NULL,'República de Sudán del Sur','South Sudan','Soudan du Sud','SS','SSD','211');
INSERT INTO `paises` VALUES(NULL,'Reunión','Réunion','Réunion','RE','REU','262');
INSERT INTO `paises` VALUES(NULL,'Ruanda','Rwanda','Rwanda','RW','RWA','250');
INSERT INTO `paises` VALUES(NULL,'Rumanía','Romania','Roumanie','RO','ROU','40');
INSERT INTO `paises` VALUES(NULL,'Rusia','Russia','La Russie','RU','RUS','7');
INSERT INTO `paises` VALUES(NULL,'Sahara Occidental','Western Sahara','Sahara Occidental','EH','ESH','212');
INSERT INTO `paises` VALUES(NULL,'Samoa','Samoa','Samoa','WS','WSM','685');
INSERT INTO `paises` VALUES(NULL,'Samoa Americana','American Samoa','Les Samoa américaines','AS','ASM','1 684');
INSERT INTO `paises` VALUES(NULL,'San Bartolomé','Saint Barthélemy','Saint-Barthélemy','BL','BLM','590');
INSERT INTO `paises` VALUES(NULL,'San Cristóbal y Nieves','Saint Kitts and Nevis','Saint Kitts et Nevis','KN','KNA','1 869');
INSERT INTO `paises` VALUES(NULL,'San Marino','San Marino','San Marino','SM','SMR','378');
INSERT INTO `paises` VALUES(NULL,'San Martín (Francia);','Saint Martin (French part);','Saint-Martin (partie française);','MF','MAF','1 599');
INSERT INTO `paises` VALUES(NULL,'San Pedro y Miquelón','Saint Pierre and Miquelon','Saint-Pierre-et-Miquelon','PM','SPM','508');
INSERT INTO `paises` VALUES(NULL,'San Vicente y las Granadinas','Saint Vincent and the Grenadines','Saint-Vincent et Grenadines','VC','VCT','1 784');
INSERT INTO `paises` VALUES(NULL,'Santa Elena','Ascensión y Tristán de Acuña','Ascensión y Tristan de Acuña','SH','SHN','290');
INSERT INTO `paises` VALUES(NULL,'Santa Lucía','Saint Lucia','Sainte-Lucie','LC','LCA','1 758');
INSERT INTO `paises` VALUES(NULL,'Santo Tomé y Príncipe','Sao Tome and Principe','Sao Tomé et Principe','ST','STP','239');
INSERT INTO `paises` VALUES(NULL,'Senegal','Senegal','Sénégal','SN','SEN','221');
INSERT INTO `paises` VALUES(NULL,'Serbia','Serbia','Serbie','RS','SRB','381');
INSERT INTO `paises` VALUES(NULL,'Seychelles','Seychelles','Les Seychelles','SC','SYC','248');
INSERT INTO `paises` VALUES(NULL,'Sierra Leona','Sierra Leone','Sierra Leone','SL','SLE','232');
INSERT INTO `paises` VALUES(NULL,'Singapur','Singapore','Singapour','SG','SGP','65');
INSERT INTO `paises` VALUES(NULL,'Sint Maarten','Sint Maarten','Saint-Martin','SX','SMX','1 721');
INSERT INTO `paises` VALUES(NULL,'Siria','Syria','Syrie','SY','SYR','963');
INSERT INTO `paises` VALUES(NULL,'Somalia','Somalia','Somalie','SO','SOM','252');
INSERT INTO `paises` VALUES(NULL,'Sri lanka','Sri Lanka','Sri Lanka','LK','LKA','94');
INSERT INTO `paises` VALUES(NULL,'Sudáfrica','South Africa','Afrique du Sud','ZA','ZAF','27');
INSERT INTO `paises` VALUES(NULL,'Sudán','Sudan','Soudan','SD','SDN','249');
INSERT INTO `paises` VALUES(NULL,'Suecia','Sweden','Suède','SE','SWE','46');
INSERT INTO `paises` VALUES(NULL,'Suiza','Switzerland','Suisse','CH','CHE','41');
INSERT INTO `paises` VALUES(NULL,'Surinám','Suriname','Surinam','SR','SUR','597');
INSERT INTO `paises` VALUES(NULL,'Svalbard y Jan Mayen','Svalbard and Jan Mayen','Svalbard et Jan Mayen','SJ','SJM','47');
INSERT INTO `paises` VALUES(NULL,'Swazilandia','Swaziland','Swaziland','SZ','SWZ','268');
INSERT INTO `paises` VALUES(NULL,'Tayikistán','Tajikistan','Le Tadjikistan','TJ','TJK','992');
INSERT INTO `paises` VALUES(NULL,'Tailandia','Thailand','Thaïlande','TH','THA','66');
INSERT INTO `paises` VALUES(NULL,'Taiwán','Taiwan','Taiwan','TW','TWN','886');
INSERT INTO `paises` VALUES(NULL,'Tanzania','Tanzania','Tanzanie','TZ','TZA','255');
INSERT INTO `paises` VALUES(NULL,'Territorio Británico del Océano Índico','British Indian Ocean Territory','Territoire britannique de l océan Indien','IO','IOT','246');
INSERT INTO `paises` VALUES(NULL,'Territorios Australes y Antárticas Franceses','French Southern Territories','Terres australes françaises','TF','ATF','');
INSERT INTO `paises` VALUES(NULL,'Timor Oriental','East Timor','Timor-Oriental','TL','TLS','670');
INSERT INTO `paises` VALUES(NULL,'Togo','Togo','Togo','TG','TGO','228');
INSERT INTO `paises` VALUES(NULL,'Tokelau','Tokelau','Tokélaou','TK','TKL','690');
INSERT INTO `paises` VALUES(NULL,'Tonga','Tonga','Tonga','TO','TON','676');
INSERT INTO `paises` VALUES(NULL,'Trinidad y Tobago','Trinidad and Tobago','Trinidad et Tobago','TT','TTO','1 868');
INSERT INTO `paises` VALUES(NULL,'Tunez','Tunisia','Tunisie','TN','TUN','216');
INSERT INTO `paises` VALUES(NULL,'Turkmenistán','Turkmenistan','Le Turkménistan','TM','TKM','993');
INSERT INTO `paises` VALUES(NULL,'Turquía','Turkey','Turquie','TR','TUR','90');
INSERT INTO `paises` VALUES(NULL,'Tuvalu','Tuvalu','Tuvalu','TV','TUV','688');
INSERT INTO `paises` VALUES(NULL,'Ucrania','Ukraine','L Ukraine','UA','UKR','380');
INSERT INTO `paises` VALUES(NULL,'Uganda','Uganda','Ouganda','UG','UGA','256');
INSERT INTO `paises` VALUES(NULL,'Uruguay','Uruguay','Uruguay','UY','URY','598');
INSERT INTO `paises` VALUES(NULL,'Uzbekistán','Uzbekistan','L Ouzbékistan','UZ','UZB','998');
INSERT INTO `paises` VALUES(NULL,'Vanuatu','Vanuatu','Vanuatu','VU','VUT','678');
INSERT INTO `paises` VALUES(NULL,'Venezuela','Venezuela','Venezuela','VE','VEN','58');
INSERT INTO `paises` VALUES(NULL,'Vietnam','Vietnam','Vietnam','VN','VNM','84');
INSERT INTO `paises` VALUES(NULL,'Wallis y Futuna','Wallis and Futuna','Wallis et Futuna','WF','WLF','681');
INSERT INTO `paises` VALUES(NULL,'Yemen','Yemen','Yémen','YE','YEM','967');
INSERT INTO `paises` VALUES(NULL,'Yibuti','Djibouti','Djibouti','DJ','DJI','253');
INSERT INTO `paises` VALUES(NULL,'Zambia','Zambia','Zambie','ZM','ZMB','260');
INSERT INTO `paises` VALUES(NULL,'Zimbabue','Zimbabwe','Zimbabwe','ZW','ZWE','263');